# Generated by Django 4.2.11 on 2024-04-06 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_user_is_trusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 4, 6, 18, 47, 55, 383380)),
        ),
    ]
